### ISSUE TITLE
Unable to Edit squid.conf

### ISSUE THREAD

**Issue by battosai-slayer864** [Hawaiideveloper/Infastructure-as-Code-Sample_Env#29]
I'm trying to edit the squid.conf. BUT no matter what I try, I doesn't let me. I am logged in the following dir root@5e742d2fb94f:~#` as the video shows.
Here are the commands I tried so far. 

NOTE: `apt-get update` was ran before attempting to install any of the below.

`apt-get install vim`
`apt-get install gedit`
`vim etc/squid/squid.conf`
`gedit etc/squid/squid.conf` 
`gksu gedit squid.conf`

When trying to install vim and gedit, it gives me a series of errors. Installing vim or gedit definitely works when I'm on regular terminal.  But that would defeat the purpose of editing squid on the running container.

**Comment by battosai-slayer864** [comment]
These are the errors that come up:

`E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gst-plugins-base1.0/gstreamer1.0-x_1.8.3-1ubuntu0.2_amd64.deb  404  Not Found [IP: 91.189.88.142 80]`

`E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by battosai-slayer864** [comment]
It worked for me after rebooting my laptop.

Then, `I did apt-get update`
`apt-get install vim` and was able to get edit access to the squid.conf file

**Comment by Hawaiideveloper** [comment]
Resolved:

See above
