### ISSUE TITLE
Editar archivos dentro de una imagen docker?

### ISSUE THREAD

**Issue by ervinj1998** [Hawaiideveloper/Infastructure-as-Code-Sample_Env#30]
Si queremos iniciar una imagen ya existente solo ingresamos el comando docker:
start "IDImage"

Algunas imagenes docker no traen editor de archivo , pero puedes añadir esta opcion o la que prefieras, en mi caso personal usé vim con los siguientes comandos:

apt-get update
apt-get install vim

usamos estos comandos para poder editar el archivo de configuracion en nuestro proxy privado, recordemos que una vez editado habra que reiniciar la imagen docker, podemos hacer esto con el siguiente comando:

docker restart IdImages

una vez dentro de la consola intereactiva del contenedor docker, para salirnos sin detener la ejecucion del contenedor , usamos el comando "ctrl+pq" al mismo tiempo

**Comment by Hawaiideveloper** [comment]
Information no review needed
